config/routes.rb
Rails.application.routes.draw do

 
  match '/oauth2callback', :to => 'oauth2_callbacks#google', :as => 'google_oauth2', :via => [:get]

  match '/payments/payment', :to => 'payments#payment', :as => 'paymentspayment', :via => [:get]
  match '/payments/relay_response', :to => 'payments#relay_response', :as => 'payments_relay_response', :via => [:post]
  match '/payments/receipt', :to => 'payments#receipt', :as => 'payments_receipt', :via => [:get]
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  root 'home#index'

  items = %w( horses studs trailers tacks real_estates services )
 
  items.each do |item|
    resources item.to_sym do
      collection do
        get 'search'
        get 'youtube_upload'
      end
      member do
        get 'search'
      end
    end
  end
 
  resources :packages do
    items.each do |item|
      resources item.to_sym, shallow: true do
        member do
          get 'preview', to: "#{item}#preview"
          get 'publish', to: "#{item}#publish"
          get 'unpublish', to: "#{item}#unpublish"
          get 'sold', to: "#{item}#sold"
          get 'activate', to: "#{item}#activate"
          get 'unactivate', to: "#{item}#unactivate"
          get 'mark-sold', to: "#{item}#mark_sold"
        end
      end
    end
  end

  resources :users do
    items.each do |item|
      resources item.to_sym do
        member do
          get "like"
          get "dislike"
        end
      end
    end 
  end

  resources :profiles do
    member do
      get 'ads'
      get 'about'
      get 'favorites'
    end
    collection do
      get 'ads'
      get 'about'
      get 'favorites'
    end
  end


  get 'pricing' => 'home#pricing', :as => :pricing

  get 'search-horses' => 'home#horses', as: :home_horses
  get 'search-studs' => 'home#studs', as: :home_studs
  get 'search-tacks' => 'home#tacks', as: :home_tacks
  get 'search-real-estates' => 'home#real_estates', as: :home_real_estates
  get 'search-services' => 'home#services', as: :home_services
  get 'search-trailers' => 'home#trailers', as: :home_trailers

  get 'horses-result' => 'home#horses_result', as: :horses_result
  get 'horses-filter' => 'home#horses_filter', as: :horses_filter

  get 'studs-result' => 'home#studs_result', as: :studs_result
  get 'studs-filter' => 'home#studs_filter', as: :studs_filter

  get 'trailers-result' => 'home#trailers_result', as: :trailers_result
  get 'trailers-filter' => 'home#trailers_filter', as: :trailers_filter

  get 'tacks-result' => 'home#tacks_result', as: :tacks_result
  get 'tacks-filter' => 'home#tacks_filter', as: :tacks_filter

  get 'real_estates-result' => 'home#real_estates_result', as: :real_estates_result
  get 'real_estates-filter' => 'home#real_estates_filter', as: :real_estates_filter

  get 'services-result' => 'home#services_result', as: :services_result
  get 'services-filter' => 'home#services_filter', as: :services_filter

end

app/models/tack.rb
class Tack < ActiveRecord::Base
	include AASM

	belongs_to :package
	belongs_to :user
	has_many :pictures, as: :imageable, dependent: :destroy
	has_many :videos, as: :videoable, dependent: :destroy

	has_many :disciplines, as: :discipline, dependent: :destroy

	accepts_nested_attributes_for :disciplines


	#validates :title, :description, :price, :user_name, :email, presence: true

	#validates :email, :email_format => {:message => 'is not looking good'}

  #validates :price, numericality: { greater_than_or_equal_to: 0 }

	is_impressionable :counter_cache => true, :column_name => :views_count, :unique => :ip_address
	acts_as_votable

	aasm column: 'status' do
    state :draft, initial: true
    state :published
    state :sold
    state :removed

    event :publish do
      transitions from: :draft, to: :published
    end

    event :remove do
      transitions from: :published, to: :removed
    end

    event :make_draft do
      transitions from: :published, to: :draft
    end

    event :make_sold do
      transitions from: :published, to: :sold
    end

    event :to_sold do
      transitions from: :removed, to: :sold
    end

  end



	scope :live, -> { where("published_end > ?", "%#{DateTime.now}%" ) }

	scope :published, -> { where(status: 'published') }

	featured_packages = ["Deluxe", "Premium"]
	scope :featured_ad, -> { where(package_id: Package.where(name: featured_packages).map(&:id)) }
	
	scope :newest_ad, -> { order(published_at: :desc) }

	scope :favorited_by, ->(user) { where(id: user.find_liked_items.map(&:id)) }

	
	def ad_banner
		self.pictures.find(self.banner) if self.pictures.present?
	end
end

app/controllers/tacks_controller.rb
class TacksController < ApplicationController
  before_action :set_user, only: [:like, :dislike]
  before_action :set_tack, except: [:index, :create, :search, :new]
  before_action :authenticate_user!, only: [:new, :like, :dislike]
  before_action :set_items_gallery, only: [:show, :preview]

  impressionist :actions=>[:show]

  include SmartListing::Helper::ControllerExtensions
  helper  SmartListing::Helper

  # GET /tacks
  def index
    @tacks = Tack.all
  end

  # GET /tacks/1
  def show
  end

  # GET /packages/:package_id/tacks/new
  def new
    @tack = Package.find(params[:package_id]).tacks.new
    @tack.disciplines.new
    gon.image_upload_limit = @tack.package.max_photo_upload
    gon.video_upload_limit = @tack.package.max_video_upload
  end

  # GET /tacks/:id/edit
  def edit
  end

  # POST /packages/:package_id/tacks
  # TODO -> Refactor this method
  def create
    @tack = Tack.new(tack_params)
    @tack.user_id = current_user.id

    respond_to do |format|
      if @tack.save
      	unless params[:tack][:pictures].nil?
          params[:tack][:pictures].each do |picture|
            @tack.pictures.create(name: picture)
          end
          @tack.update(banner: @tack.pictures.first.id)
        end

        unless params[:tack][:videos].nil?
          params[:tack][:videos].each do |video|
            @tack.videos.create(name: picture)
          end
        end

        format.html { redirect_to preview_tack_url(@tack), notice: 'Ad Horse Saved!' }
      else
        format.html { render :new, notice: 'Save Tack Failed!' }
      end
    end
  end

  # PATCH/PUT /tacks/:id
  # TODO -> update for tacks picture & video
  def update
    respond_to do |format|
      if @tack.update(tack_params)
        format.html { redirect_to preview_tack_url(@tack), notice: 'Tack was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /tacks/1
  def destroy
    @tack.destroy
    respond_to do |format|
      format.html { redirect_to ads_profiles_url }
    end
  end

  # GET /tacks/:id/preview
  def preview
  end

  # PUT /tacks/:id/publish
  def publish
  end

  # GET /tacks/:id/unpublish
  def unpublish
  end

  # GET /horses/:id/activate
  def activate
    respond_to do |format|
      if @tack.draft?
        @tack.publish!
        @tack.update(published_at: DateTime.now,
          published_end: DateTime.now + @tack.package.duration.month)
        format.html { redirect_to @tack, notice: 'Ad was successfully published.' }
      else
        format.html { render :preview }
      end
    end
  end

  # GET /horses/:id/unactivate
  def unactivate
    respond_to do |format|
      if @tack.published?
        @tack.remove!
        format.html { redirect_to ads_profiles_url, notice: 'Ad was successfully unpublished.' }
      else
        format.html { redirect_to unpublish_tack_url }
      end
    end
  end

  # GET /horses/:id/sold
  def sold
  end

  # GET /horses/:id/mark-sold
  def mark_sold
    respond_to do |format|
      if @tack.published? || @tack.removed?
        @tack.make_sold! if @tack.published?
        @tack.to_sold! if @tack.removed?
        format.html { redirect_to ads_profiles_url, notice: 'Ad was successfully Mark As Sold' }
      else
        format.html { redirect_to sold_tack_url }
      end
    end
  end

  def like
    @tack.liked_by @user
  end

  def dislike
    @tack.unliked_by @user
  end

  def search
    unless params[:q].blank?
      @params_q = params[:q]
      @tacks = Tack.search(params[:q]).result
    else
      @tacks =  Tack.all
    end

    sort_by = {updated_at: :desc} if params[:sort_by] == "newest" || params[:sort_by].nil?
    sort_by = {updated_at: :asc} if params[:sort_by] == "oldest"
    sort_by = {price: :desc} if params[:sort_by] == "high_to_low"
    sort_by = {price: :asc} if params[:sort_by] == "low_to_high"

    @tacks = @tacks.order(sort_by).published.live

    smart_listing_create(:tacks, @tacks, partial: "tacks/tack_list")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tack
      @tack = Tack.find(params[:id])
    end

    def set_user
      @user = User.find(params[:user_id])
    end

    def set_items_gallery
      @items_gallery = @tack.pictures + @tack.videos
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tack_params
      params.require(:tack).permit(:title, :description, :price, :tack, :type, :condition, :color,
        :user_name, :farm_name, :email, :website, :phone_number, :alt_phone_number, :package_id,
        disciplines_attributes: [:id, :name, :experience, :_destroy])
    end
    
end

app/helpers/tacks_helper.rb
module TacksHelper
end

app/views/tacks/_form.html.slim
= simple_nested_form_for @tack, :html => {:multipart => true,  class: 'form-horizontal'} do |f|

  - if @tack.errors.any?
    #error_explanation
      h2 = "#{pluralize(@tack.errors.count, "error")} prohibited this tack from being saved:"
      ul
        - @tack.errors.full_messages.each do |message|
          li = message

  .document.border-bottom
    .document-wrapper.border
      .text.ten
        h2.followon The Basics About Your Tack

        .row        
          = f.hidden_field :package_id, value: @tack.package_id
          = f.input :title, label: false, placeholder: "Ad Title * - Captive Your Buyer"
          = f.input :description, label: false,  placeholder: "About Your Tack *", input_html: { rows: 8 }

        .row
        	= f.input :tack, label: false, wrapper_html: { class: 'col-md-4' }, prompt: "Tack", collection: TackOption.all, value_method: :name
        	= f.input :tack_type, label: false, wrapper_html: { class: 'col-md-4' }, prompt: "Type", collection: TackTypeOption.all, value_method: :name
        	= f.input :price, label: false, wrapper_html: { class: 'col-md-4' }, placeholder: "Price"

        .row
        	= f.input :condition, label: false, wrapper_html: { class: 'col-md-4' }, placeholder: "Condition"
        	= f.input :color, label: false, wrapper_html: { class: 'col-md-4' }, placeholder: "Color"

        h3 Disciplines

        = f.simple_fields_for :disciplines do |fd|
          .row
            = fd.input :name, label: false, wrapper_html: { class: 'col-md-6' }, prompt: "Discipline (optional)", collection: DisciplineOption.all, value_method: :name
            = fd.input :experience, label: false, wrapper_html: { class: 'col-md-6' }, prompt: "Experience (optional)", collection: ExperienceOption.all, value_method: :name

        p.count.cap 
          = f.link_to_add "+ Add Another Discipline", :disciplines
 

  - unless @tack.package.name == "Basic"
    = render "shared/form/input_file", f: f

  = render "shared/form/contact_info", f: f
  
  = render "shared/form/terms_and_conditions", f: f

  = render "shared/form/submit_button", f: f
  
  p.count.terms_cond.center 
    | By clicking Save &amp; Preview, you are agreeing to Mountseek's 
    br
    = link_to "Terms & Conditions", "#"

  .button-container
    = f.button :submit, 'Save & Preview', class: "btn btn-lg btn-submit"

app/views/tacks/_tack_detail.html.slim
.row
  .col-md-6
    - unless @tack.ad_banner.nil?
      img src= @tack.ad_banner.name.thumb.url
    - else
      =image_tag( 'tack.jpg')
  .col-md-6
    h4 
      - unless @tack.title.nil?
        = @tack.title
      - else
        | UNNAMED
    .price
			= number_to_currency @tack.price

    hr

    .short_detail

      = "Sale by #{@tack.user.username}"

.row
  .col-md-12.stats
    h4 TRAILER STATS
    hr
    table.table.table-striped
      tr
        td Name

      tr
        td Color     

.row
  .col-md-12
    h4= @tack.title.upcase
    hr
    p= @tack.description

.row
  .col-md-12.galleries
    h4 PHOTO & VIDEO GALLERY
    hr
    - @items_gallery.in_groups_of(4).each do |item_group|
      .row
        - item_group.each do |item|
          - unless item.nil?
            .col-md-3
              =image_tag item.name.thumb

.row
  .col-md-12
    h4 CONTACT SELLER
    hr
    - if @tack.user.profile.user_picture.present?
      img src=  @tack.user.profile.user_picture.avatar.url
    - else
      .fa-stack.fa-4x
        i.fa.fa-circle.fa-stack-2x
        i.fa.fa-user.fa-stack-1x.fa-inverse

   
      p= "FOR SALE BY #{@tack.user_name.upcase}"

    - if @tack.user.profile.state && @tack.user.profile.city
      p= "#{@tack.user.profile.state}, #{@tack.user.profile.city}"

    ul.nav.nav-tabs
      li
        i.fa.fa-envelope.fa-2x
        br EMAIL SELLER
      | &nbsp;&nbsp;
      - if @tack.phone_number.present?
        li
          i.fa.fa-phone.fa-2x&nbsp
          br= @tack.phone_number
        | &nbsp;&nbsp;
      li
        =link_to ads_profile_path(@tack.user)
          i.fa.fa-bookmark.fa-2x&nbsp
          br VIEW ALL ADS
      | &nbsp;&nbsp;
      - if @tack.website.present?
        li
          a href="http://#{@tack.website}"
            i.fa.fa-globe.fa-2x&nbsp
            br VIEW WEBSITE

app/views/tacks/_tack_list.html.slim
- unless smart_listing.empty? 
  - smart_listing.collection.in_groups_of(4).each do |tacks_group|
    .row
      ul.thumbnails
        - tacks_group.each do |tack|
          - unless tack.nil?
            .li.col-md-3
              = render partial: "shared/tack_thumbnail", locals: {tack: tack}
  = smart_listing.paginate

app/views/tacks/edit.html.slim
.container
  .form-wrapper
  	== render 'form'

app/views/tacks/new.html.slim
section#profile
	.container
		header.profile_header
			h1= "Create Your #{@tack.package.name} Tack Ad"
		.outer
			.inner.pt-0
				= render "form"

= include_gon
= javascript_include_tag 'inspect_file_upload_limit', 'data-turbolinks-track' => true

app/views/tacks/preview.html.slim
.container
  .preview-wrapper
    h1 Preview Your Draft
    
    = render "tack_detail"
          
    = link_to 'Edit', edit_tack_path(@tack), class: "btn btn-primary btn-inverse"
    | &nbsp;
    = link_to 'Publish Ad', publish_tack_path(@tack), class: "btn btn-primary btn-inverse"

app/views/tacks/publish.html.slim
.container
  .publish-wrapper
    h1 Publish Your Tack

    - unless @tack.ad_banner.nil?
      img src= @tack.ad_banner.name.thumb.url
    

    p= "#{@tack.package.name} Ad Package"
    p= "TOTAL #{number_to_currency @tack.package.price}"

    h4= "YOUR #{@tack.package.name.upcase} AD INCLUDES"
    ul
    	li= "#{@tack.package.duration} Month Ad Duration"
    	- if @tack.package.max_photo_upload > 0
    		li= "Up To #{@tack.package.max_photo_upload} Photos"
    	- if @tack.package.max_video_upload > 0
    		li= "Up To #{@tack.package.max_video_upload} Videos"

          
    = link_to 'Edit', edit_tack_path(@tack), class: "btn btn-primary btn-inverse"
    | &nbsp;
    = link_to 'Publish', activate_tack_path(@tack), class: "btn btn-primary btn-inverse"

app/views/tacks/search.html.slim
.container
  h4= "#{@tacks.count} Tacks Found" 

  .row.filter
    .col-md-10

    .col-md-2
      = smart_listing_controls_for(:tacks, {class: "form-inline text-right"}) do
        =select_tag :sort_by, options_for_select([["Newest", "newest"], ["Oldest", "oldest"], ["Price High to Low", "high_to_low"], ["Price Low to High", "low_to_high"] ], "newest"), { class: 'form-control' } 

        - unless @params_q.nil?
          =hidden_field_tag "q[tack_cont]", @params_q["tack_cont"]
          =hidden_field_tag "q[condition_cont]", @params_q["condition_cont"]

  = smart_listing_render :tacks
  
= javascript_include_tag 'fav_button', 'data-turbolinks-track' => true

app/views/tacks/search.js.erb
<%# Render list for XHR requests %>
<%= smart_listing_update :tacks %>

app/views/tacks/show.html.slim
.container
  h1 Show Tack
  = render "tack_detail"

app/views/tacks/sold.html.slim
.container
  .sold-wrapper
    h1 MARK YOUR AD AS SOLD

    h4 CONGRATULATIONS ON SELLING YOUR TACK!

    = link_to 'Cancel', ads_profiles_path, class: "btn"
    = link_to 'Mark As Sold', mark_sold_tack_path(@tack), class: "btn"

app/views/tacks/unpublish.html.slim
.container
  .unpublish-wrapper
    h1 Unpublish Your TACK

    p 
      | Unpublishing your ad will hide it from public view. However, you will be able to republish it at any time before your ad's expiration date.

    = link_to 'Cancel', ads_profiles_path, class: "btn"
    = link_to 'Unpublish', unactivate_real_tack_path(@tack), class: "btn"