config/routes.rb
Rails.application.routes.draw do

 
  match '/oauth2callback', :to => 'oauth2_callbacks#google', :as => 'google_oauth2', :via => [:get]

  match '/payments/payment', :to => 'payments#payment', :as => 'paymentspayment', :via => [:get]
  match '/payments/relay_response', :to => 'payments#relay_response', :as => 'payments_relay_response', :via => [:post]
  match '/payments/receipt', :to => 'payments#receipt', :as => 'payments_receipt', :via => [:get]
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  root 'home#index'

  items = %w( horses studs trailers tacks real_estates services )
 
  items.each do |item|
    resources item.to_sym do
      collection do
        get 'search'
        get 'youtube_upload'
      end
      member do
        get 'search'
      end
    end
  end
 
  resources :packages do
    items.each do |item|
      resources item.to_sym, shallow: true do
        member do
          get 'preview', to: "#{item}#preview"
          get 'publish', to: "#{item}#publish"
          get 'unpublish', to: "#{item}#unpublish"
          get 'sold', to: "#{item}#sold"
          get 'activate', to: "#{item}#activate"
          get 'unactivate', to: "#{item}#unactivate"
          get 'mark-sold', to: "#{item}#mark_sold"
        end
      end
    end
  end

  resources :users do
    items.each do |item|
      resources item.to_sym do
        member do
          get "like"
          get "dislike"
        end
      end
    end 
  end

  resources :profiles do
    member do
      get 'ads'
      get 'about'
      get 'favorites'
    end
    collection do
      get 'ads'
      get 'about'
      get 'favorites'
    end
  end


  get 'pricing' => 'home#pricing', :as => :pricing

  get 'search-horses' => 'home#horses', as: :home_horses
  get 'search-studs' => 'home#studs', as: :home_studs
  get 'search-tacks' => 'home#tacks', as: :home_tacks
  get 'search-real-estates' => 'home#real_estates', as: :home_real_estates
  get 'search-services' => 'home#services', as: :home_services
  get 'search-trailers' => 'home#trailers', as: :home_trailers

  get 'horses-result' => 'home#horses_result', as: :horses_result
  get 'horses-filter' => 'home#horses_filter', as: :horses_filter

  get 'studs-result' => 'home#studs_result', as: :studs_result
  get 'studs-filter' => 'home#studs_filter', as: :studs_filter

  get 'trailers-result' => 'home#trailers_result', as: :trailers_result
  get 'trailers-filter' => 'home#trailers_filter', as: :trailers_filter

  get 'tacks-result' => 'home#tacks_result', as: :tacks_result
  get 'tacks-filter' => 'home#tacks_filter', as: :tacks_filter

  get 'real_estates-result' => 'home#real_estates_result', as: :real_estates_result
  get 'real_estates-filter' => 'home#real_estates_filter', as: :real_estates_filter

  get 'services-result' => 'home#services_result', as: :services_result
  get 'services-filter' => 'home#services_filter', as: :services_filter

end

app/views/shared/_horse_thumbnail.html.slim
.ad-thumbnail.thumbnail
  - if current_user
    - if current_user.voted_up_on? horse
        =link_to raw("<i class='fa fa-heart'></i>"), "javascript:void(0)", :title => 'Remove From My Favorites', id: "fav-horse-#{horse.id}", class: 'fav-horse-button', data: {url: dislike_user_horse_path(current_user, horse), toggle: 'tooltip', placement: 'bottom'}
    - else
        =link_to raw("<i class='fa fa-heart'></i>"), "javascript:void(0)", :title => 'Ad To My Favorites', id: "fav-horse-#{horse.id}", class: 'fav-horse-button', data: {url: like_user_horse_path(current_user, horse), toggle: 'tooltip', placement: 'bottom'}        
  - else
    =link_to raw("<span class='fa fa-heart'></span>"), new_user_session_path , :title => 'Log In To Favorite Horse', class: 'fav-icon like-horse-button', data: {toggle: 'tooltip', placement: 'bottom'}

  span.price.pull-right= number_to_currency horse.price
  .ad-title= horse.title
  - unless horse.ad_banner.nil?
    =link_to image_tag(horse.ad_banner.name.thumb), horse
  - else
    =link_to image_tag("horse1.jpg"), horse
  .row
    .col-md-6
      ul
        li="Gender: #{horse.gender}"
        li="Breed: #{horse.breed}"
        li="Age: #{horse.birth}"
    .col-md-6
      ul
        li="Color: #{horse.color}"
        li="Height: #{horse.height} hands"
        li="Weight: #{horse.weight} lbs"
  .ad-properties.pull-right
    i.fa.fa-eye
      ="#{horse.impressionist_count(:filter=>:ip_address)}"
      | &nbsp;
    i.fa.fa-heart class="like-count-#{horse.id}"
      ="#{horse.get_likes.size}"
      | &nbsp;
    i.fa.fa-camera
      ="#{horse.pictures.size}"
      | &nbsp;
    i.fa.fa-video-camera
      | &nbsp;
  hr
  p= truncate horse.description, size: 100
  =social_share_button_tag(horse.title, :url => horse_url(horse))


  

app/views/shared/_horses_search_category.html.erb
<div class="row-fluid">
  <div class="span6">
		<form>
			<h4><i class="icon-tint"></i> Breeds</h4>
			<div class="row-fluid">
      	<div class="span6">
			    <label class="checkbox">
			      <input type="checkbox"> Any Breed
			    </label>
			    <label class="checkbox">
			      <input type="checkbox"> Arabian
			    </label>
			    <label class="checkbox">
			      <input type="checkbox"> Big Hair
			    </label>
			    <label class="checkbox">
			      <input type="checkbox"> Colors & Spots
			    </label>
			    <label class="checkbox">
			      <input type="checkbox"> Drafts
			    </label>
			    <label class="checkbox">
			      <input type="checkbox"> Gaited
			    </label>
			    <label class="checkbox">
			      <input type="checkbox"> Baroque
			    </label>
			    <label class="checkbox">
			      <input type="checkbox"> Mustang
			    </label>
      	</div>

      	<div class="span6">
			    <label class="checkbox">
			      <input type="checkbox"> Pinto
			    </label>
			    <label class="checkbox">
			      <input type="checkbox"> Quarter Horse
			    </label>
			    <label class="checkbox">
			      <input type="checkbox"> Rare & Exotic
			    </label>
			    <label class="checkbox">
			      <input type="checkbox"> Warmblood
			    </label>
			    <label class="checkbox">
			      <input type="checkbox"> Thoroughbred
			    </label>
			    <label class="checkbox">
			      <input type="checkbox"> Working Horse
			    </label>
			    <label class="checkbox">
			      <input type="checkbox"> Non Horse
			    </label>
      	</div>
      </div>
  	</form>
  </div>
  <div class="span6">
		<form>
			<h4><i class="icon-tags"></i> Genders</h4>
			<div class="row-fluid">
      	<div class="span6">
      		<label class="checkbox">
			      <input type="checkbox"> Any Gender
			    </label>
			    <label class="checkbox">
			      <input type="checkbox"> Males
			    </label>
			    <label class="checkbox">
			      <input type="checkbox"> Females
			    </label>
			    <label class="checkbox">
			      <input type="checkbox"> Fillies
			    </label>
			    <label class="checkbox">
			      <input type="checkbox"> Geldings
			    </label>
			    <label class="checkbox">
			      <input type="checkbox"> Ridglings
			    </label>
			     <label class="checkbox">
			      <input type="checkbox"> Mares
			    </label>
			    <label class="checkbox">
			      <input type="checkbox"> Stallions
			    </label>
      	</div>

      	<div class="span6">
			    <label class="checkbox">
			      <input type="checkbox"> Uboarn Foals
			    </label>
			    <label class="checkbox">
			      <input type="checkbox"> Broodmares
			    </label>
			    <label class="checkbox">
			      <input type="checkbox"> Ridglings
			    </label>
			    <label class="checkbox">
			      <input type="checkbox"> Weanlings
			    </label>
			    <label class="checkbox">
			      <input type="checkbox"> Yearlings
			    </label>
			    <label class="checkbox">
			      <input type="checkbox"> Folas
			    </label>
			    <label class="checkbox">
			      <input type="checkbox"> Unknown
			    </label>

      	</div>
    	</div>
  	</form>
  </div>
</div>
<hr class="divider">

app/views/shared/_locations_search_category.html.erb
<div class="row">
	<div class="col-md-12">
		<form>
			<h4><i class="icon-globe"></i> Locations</h4>
    	<div class="col-md-2">
		    <label class="checkbox">
		      <input type="checkbox"> Any Location
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> Arabian
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> Alaska
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> Arizona
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> Arkansas
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> California
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> Colorado
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> Delaware
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> Florida
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> Georgia
		    </label>
    	</div>

    	<div class="col-md-2">
		    <label class="checkbox">
		      <input type="checkbox"> Hawai
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> Idaho
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> Illinois
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> Indiana
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> Iowa
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> Kansas
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> Kentucky
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> Lousiana
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> Maine
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> Maryland
		    </label>
    	</div>

    	<div class="col-md-2">
		    <label class="checkbox">
		      <input type="checkbox"> Massachussets
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> Michigan
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> Minnesota
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> Mississippi
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> Missouri
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> Montana
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> Nebraska
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> Nevada
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> New Hampshire
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> New Jersey
		    </label>
    	</div>

    	<div class="col-md-2">
		    <label class="checkbox">
		      <input type="checkbox"> New Mexico
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> New York
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> North Carolina
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> North Dakota
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> Ohio
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> Oklahoma
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> Oregon
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> Pennsylvania
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> Rhode Island
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> South Carolina
		    </label>
    	</div>

    	<div class="col-md-2">
		    <label class="checkbox">
		      <input type="checkbox"> South Dakota
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> Tennesse
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> Texas
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> Utah
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> Vermont
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> Virginia
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> Washington
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> West Virginia
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> Wiconsin
		    </label>
		    <label class="checkbox">
		      <input type="checkbox"> Wyoming
		    </label>
    	</div>
  	</form>
	</div>
</div>
<hr class="divider">

app/views/shared/_real_estate_thumbnail.html.slim
.ad-thumbnail.thumbnail
  - if current_user
    - if current_user.voted_up_on? real_estate
        =link_to raw("<i class='fa fa-heart'></i>"), "javascript:void(0)", :title => 'Remove From My Favorites', id: "fav-real_estate-#{real_estate.id}", class: 'fav-real_estate-button', data: {url: dislike_user_real_estate_path(current_user, real_estate), toggle: 'tooltip', placement: 'bottom'}
    - else
        =link_to raw("<i class='fa fa-heart'></i>"), "javascript:void(0)", :title => 'Ad To My Favorites', id: "fav-real_estate-#{real_estate.id}", class: 'fav-real_estate-button', data: {url: like_user_real_estate_path(current_user, real_estate), toggle: 'tooltip', placement: 'bottom'}        
  - else
    =link_to raw("<span class='fa fa-heart'></span>"), new_user_session_path , :title => 'Log In To Favorite Horse', class: 'fav-icon like-real_estate-button', data: {toggle: 'tooltip', placement: 'bottom'}

  span.price.pull-right= number_to_currency real_estate.price
  .ad-title= real_estate.title
  - unless real_estate.ad_banner.nil?
    =link_to image_tag(real_estate.ad_banner.name.thumb), real_estate
  - else
    =link_to image_tag("real_estate1.jpg"), real_estate
  .row
    .col-md-6
      ul
        li="Year: #{real_estate.year}"
        li="Type: #{real_estate.house_type}"
        li="Floor: #{real_estate.floor}"
    .col-md-6
      ul
        li="Acres: #{real_estate.total_acres}"
      	li="Bedroom: #{real_estate.bedroom}"
        li="Bathroom: #{real_estate.bathroom}"
        
  .ad-properties.pull-right
    i.fa.fa-eye
      ="#{real_estate.impressionist_count(:filter=>:ip_address)}"
      | &nbsp;
    i.fa.fa-heart class="like-count-#{real_estate.id}"
      ="#{real_estate.get_likes.size}"
      | &nbsp;
    i.fa.fa-camera
      ="#{real_estate.pictures.size}"
      | &nbsp;
    i.fa.fa-video-camera
      | &nbsp;
  hr
  p= truncate real_estate.description, size: 100

  =social_share_button_tag(real_estate.title, :url => real_estate_url(real_estate))

app/views/shared/_search_category_button.html.erb
<button type="submit" class="btn btn-primary" type="button"><i class="icon-search"></i> See Results</button>
<hr class="divider">

app/views/shared/_service_thumbnail.html.slim
.ad-thumbnail.thumbnail
  - if current_user
    - if current_user.voted_up_on? service
        =link_to raw("<i class='fa fa-heart'></i>"), "javascript:void(0)", :title => 'Remove From My Favorites', id: "fav-service-#{service.id}", class: 'fav-service-button', data: {url: dislike_user_service_path(current_user, service), toggle: 'tooltip', placement: 'bottom'}
    - else
        =link_to raw("<i class='fa fa-heart'></i>"), "javascript:void(0)", :title => 'Ad To My Favorites', id: "fav-service-#{service.id}", class: 'fav-service-button', data: {url: like_user_service_path(current_user, service), toggle: 'tooltip', placement: 'bottom'}        
  - else
    =link_to raw("<span class='fa fa-heart'></span>"), new_user_session_path , :title => 'Log In To Favorite Horse', class: 'fav-icon like-service-button', data: {toggle: 'tooltip', placement: 'bottom'}

  span.price.pull-right
  .ad-title= service.title
  - unless service.ad_banner.nil?
    =link_to image_tag(service.ad_banner.name.thumb), service
  - else
    =link_to image_tag("service1.jpg"), service
  .row
    .col-md-6
      ul
        li="Type: #{service.service_type}"

    .col-md-6
      ul
        li="Company: #{service.company}"

  .ad-properties.pull-right
    i.fa.fa-eye
      ="#{service.impressionist_count(:filter=>:ip_address)}"
      | &nbsp;
    i.fa.fa-heart class="like-count-#{service.id}"
      ="#{service.get_likes.size}"
      | &nbsp;
    i.fa.fa-camera
      ="#{service.pictures.size}"
      | &nbsp;
    i.fa.fa-video-camera
      | &nbsp;
  hr
  p= truncate service.description, size: 100
  =social_share_button_tag(service.title, :url => service_url(service))


  

app/views/shared/_tack_thumbnail.html.slim
.ad-thumbnail.thumbnail
  - if current_user
    - if current_user.voted_up_on? tack
        =link_to raw("<i class='fa fa-heart'></i>"), "javascript:void(0)", :title => 'Remove From My Favorites', id: "fav-tack-#{tack.id}", class: 'fav-tack-button', data: {url: dislike_user_tack_path(current_user, tack), toggle: 'tooltip', placement: 'bottom'}
    - else
        =link_to raw("<i class='fa fa-heart'></i>"), "javascript:void(0)", :title => 'Ad To My Favorites', id: "fav-tack-#{tack.id}", class: 'fav-tack-button', data: {url: like_user_tack_path(current_user, tack), toggle: 'tooltip', placement: 'bottom'}        
  - else
    =link_to raw("<span class='fa fa-heart'></span>"), new_user_session_path , :title => 'Log In To Favorite Horse', class: 'fav-icon like-tack-button', data: {toggle: 'tooltip', placement: 'bottom'}

  span.price.pull-right= number_to_currency tack.price
  .ad-title= tack.title
  - unless tack.ad_banner.nil?
    =link_to image_tag(tack.ad_banner.name.thumb), tack
  - else
    =link_to image_tag("tack1.jpg"), tack
  .row
    .col-md-6
      ul
        li="Tack: #{tack.tack}"
        li="Type: #{tack.tack_type}"

    .col-md-6
      ul
        li="Condition: #{tack.condition}"

  .ad-properties.pull-right
    i.fa.fa-eye
      ="#{tack.impressionist_count(:filter=>:ip_address)}"
      | &nbsp;
    i.fa.fa-heart class="like-count-#{tack.id}"
      ="#{tack.get_likes.size}"
      | &nbsp;
    i.fa.fa-camera
      ="#{tack.pictures.size}"
      | &nbsp;
    i.fa.fa-video-camera
      | &nbsp;
  hr
  p= truncate tack.description, size: 100
  =social_share_button_tag(tack.title, :url => tack_url(tack))


  

app/views/shared/_trailer_thumbnail.html.slim
.ad-thumbnail.thumbnail
  - if current_user
    - if current_user.voted_up_on? trailer
        =link_to raw("<i class='fa fa-heart'></i>"), "javascript:void(0)", :title => 'Remove From My Favorites', id: "fav-trailer-#{trailer.id}", class: 'fav-trailer-button', data: {url: dislike_user_trailer_path(current_user, trailer), toggle: 'tooltip', placement: 'bottom'}
    - else
        =link_to raw("<i class='fa fa-heart'></i>"), "javascript:void(0)", :title => 'Ad To My Favorites', id: "fav-trailer-#{trailer.id}", class: 'fav-trailer-button', data: {url: like_user_trailer_path(current_user, trailer), toggle: 'tooltip', placement: 'bottom'}        
  - else
    =link_to raw("<span class='fa fa-heart'></span>"), new_user_session_path , :title => 'Log In To Favorite Horse', class: 'fav-icon like-trailer-button', data: {toggle: 'tooltip', placement: 'bottom'}

  span.price.pull-right= number_to_currency trailer.price
  .ad-title= trailer.title
  - unless trailer.ad_banner.nil?
    =link_to image_tag(trailer.ad_banner.name.thumb), trailer
  - else
    =link_to image_tag("trailer1.jpg"), trailer
  .row
    .col-md-6
      ul
        li="Year: #{trailer.year}"
        li="Hauls: #{trailer.hauls}"
        li="Material: #{trailer.material}"
        li="Brand: #{trailer.brand}"
    .col-md-6
      ul
      	li="Model: #{trailer.model}"
        li="Hitch: #{trailer.hitch}"
        li="Axles: #{trailer.axles}"
  .ad-properties.pull-right
    i.fa.fa-eye
      ="#{trailer.impressionist_count(:filter=>:ip_address)}"
      | &nbsp;
    i.fa.fa-heart class="like-count-#{trailer.id}"
      ="#{trailer.get_likes.size}"
      | &nbsp;
    i.fa.fa-camera
      ="#{trailer.pictures.size}"
      | &nbsp;
    i.fa.fa-video-camera
      | &nbsp;
  hr
  p= truncate trailer.description, size: 100

  =social_share_button_tag(trailer.title, :url => trailer_url(trailer))