config/routes.rb
Rails.application.routes.draw do

 
  match '/oauth2callback', :to => 'oauth2_callbacks#google', :as => 'google_oauth2', :via => [:get]

  match '/payments/payment', :to => 'payments#payment', :as => 'paymentspayment', :via => [:get]
  match '/payments/relay_response', :to => 'payments#relay_response', :as => 'payments_relay_response', :via => [:post]
  match '/payments/receipt', :to => 'payments#receipt', :as => 'payments_receipt', :via => [:get]
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  root 'home#index'

  items = %w( horses studs trailers tacks real_estates services )
 
  items.each do |item|
    resources item.to_sym do
      collection do
        get 'search'
        get 'youtube_upload'
      end
      member do
        get 'search'
      end
    end
  end
 
  resources :packages do
    items.each do |item|
      resources item.to_sym, shallow: true do
        member do
          get 'preview', to: "#{item}#preview"
          get 'publish', to: "#{item}#publish"
          get 'unpublish', to: "#{item}#unpublish"
          get 'sold', to: "#{item}#sold"
          get 'activate', to: "#{item}#activate"
          get 'unactivate', to: "#{item}#unactivate"
          get 'mark-sold', to: "#{item}#mark_sold"
        end
      end
    end
  end

  resources :users do
    items.each do |item|
      resources item.to_sym do
        member do
          get "like"
          get "dislike"
        end
      end
    end 
  end

  resources :profiles do
    member do
      get 'ads'
      get 'about'
      get 'favorites'
    end
    collection do
      get 'ads'
      get 'about'
      get 'favorites'
    end
  end


  get 'pricing' => 'home#pricing', :as => :pricing

  get 'search-horses' => 'home#horses', as: :home_horses
  get 'search-studs' => 'home#studs', as: :home_studs
  get 'search-tacks' => 'home#tacks', as: :home_tacks
  get 'search-real-estates' => 'home#real_estates', as: :home_real_estates
  get 'search-services' => 'home#services', as: :home_services
  get 'search-trailers' => 'home#trailers', as: :home_trailers

  get 'horses-result' => 'home#horses_result', as: :horses_result
  get 'horses-filter' => 'home#horses_filter', as: :horses_filter

  get 'studs-result' => 'home#studs_result', as: :studs_result
  get 'studs-filter' => 'home#studs_filter', as: :studs_filter

  get 'trailers-result' => 'home#trailers_result', as: :trailers_result
  get 'trailers-filter' => 'home#trailers_filter', as: :trailers_filter

  get 'tacks-result' => 'home#tacks_result', as: :tacks_result
  get 'tacks-filter' => 'home#tacks_filter', as: :tacks_filter

  get 'real_estates-result' => 'home#real_estates_result', as: :real_estates_result
  get 'real_estates-filter' => 'home#real_estates_filter', as: :real_estates_filter

  get 'services-result' => 'home#services_result', as: :services_result
  get 'services-filter' => 'home#services_filter', as: :services_filter

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_search_horses, only: [:horses, :horses_result, :horses_filter]
  before_action :set_search_studs, only: [:studs, :studs_result, :studs_filter]
  before_action :set_search_trailers, only: [:trailers, :trailers_result, :trailers_filter]
  before_action :set_search_tacks, only: [:tacks, :tacks_result, :tacks_filter]
  before_action :set_search_real_estates, only: [:real_estates, :real_estates_result, :real_estates_filter]
  before_action :set_search_services, only: [:services, :services_result, :services_filter]

  before_action :set_search_horses_result, only: [:horses_result, :horses_filter]
  before_action :set_search_studs_result, only: [:studs_result, :studs_filter]
  before_action :set_search_tacks_result, only: [:tacks_result, :tacks_filter]
  before_action :set_search_trailers_result, only: [:trailers_result, :trailers_filter]
  before_action :set_search_real_estates_result, only: [:real_estates_result, :real_estates_filter]
  before_action :set_search_services_result, only: [:services_result, :services_filter]

  before_action :set_breed_options, only: [:horses, :horses_result, :studs, :studs_result]
  before_action :set_gender_options, only: [:horses, :horses_result]
  before_action :set_state_options, only: [:horses , :horses_result, :studs, :studs_result, :trailers, :trailers_result, :real_estates, :real_estates_result, :services, :services_result]
  before_action :set_ai_type_options, only: [:studs, :studs_result]
  before_action :set_hauls_options, only: [:trailers, :trailers_result]
  before_action :set_tacks_options, only: [:tacks, :tacks_result]
  before_action :set_house_options, only: [:real_estates, :real_estates_result]
  before_action :set_service_options, only: [:services, :services_result]

  include SmartListing::Helper::ControllerExtensions
  helper  SmartListing::Helper

  def index
    @user = current_user
    @featured_horses = Horse.published.featured_ad.limit(20)
    @newest_horses = Horse.published.newest_ad.limit(12)
    @search_horse = Horse.search(params[:q])
    @search_stud = Stud.search(params[:q])
    @search_trailer = Trailer.search(params[:q])
    @search_real_estate = RealEstate.search(params[:q])
    @search_tack = Tack.search(params[:q])
    @search_service = Service.search(params[:q])
  end

  def pricing
    @horsePackages = Package.where(type_id: 1)
    @studPackages = Package.where(type_id: 2)
    @trailerPackages = Package.where(type_id: 4)
    @tackPackages = Package.where(type_id: 3)
    @realEstatePackages = Package.where(type_id: 5)
    @servicePackages = Package.where(type_id: 6)
  end

  def horses
  end

  def studs
  end

  def trailers
  end

  def tacks
  end

  def real_estates
    
  end

  def services
  end

  def horses_result
    smart_listing_create(:horses, @horses, partial: "home/horses/horse_list")
    if params[:q]
      gon.params_value = params[:q][:breed_cont_any] if params[:q][:breed_cont_any]
      gon.params_value += params[:q][:gender_cont_any] if params[:q][:gender_cont_any]
      gon.params_value += params[:q][:state_cont_any] if params[:q][:state_cont_any]
    end
  end

  def studs_result
    smart_listing_create(:studs, @studs, partial: "home/studs/stud_list")
    if params[:q]
      gon.params_value = params[:q][:breed_cont_any] if params[:q][:breed_cont_any]
      gon.params_value += params[:q][:ai_type_cont_any] if params[:q][:ai_type_cont_any]
      gon.params_value += params[:q][:state_cont_any] if params[:q][:state_cont_any]
    end
  end

  def trailers_result
    smart_listing_create(:trailers, @trailers, partial: "home/trailers/trailer_list")
    if params[:q]
      gon.params_value = params[:q][:hauls_eq_any] if params[:q][:hauls_eq_any]
      gon.params_value += params[:q][:state_cont_any] if params[:q][:state_cont_any]
    end
  end

  def tacks_result
    smart_listing_create(:tacks, @tacks, partial: "home/tacks/tack_list")
    if params[:q]
      gon.params_value = params[:q][:tack_cont_any] if params[:q][:tack_cont_any]
      gon.params_value += params[:q][:tack_type_cont_any] if params[:q][:tack_type_cont_any]
      gon.params_value += params[:q][:condition_cont_any] if params[:q][:condition_cont_any]
    end

  end

  def real_estates_result
    smart_listing_create(:real_estates, @real_estates, partial: "home/real_estates/real_estate_list")
    if params[:q]
      gon.params_value = params[:q][:house_type_cont_any] if params[:q][:house_type_cont_any]
      gon.params_value += params[:q][:bedroom_eq_any] if params[:q][:bedroom_eq_any]
      gon.params_value += params[:q][:state_cont_any] if params[:q][:state_cont_any]
    end
  
  end

  def services_result
    smart_listing_create(:services, @services, partial: "home/services/service_list")
    if params[:q]
      gon.params_value = params[:q][:service_type_cont_any] if params[:q][:service_type_cont_any]
      gon.params_value += params[:q][:state_cont_any] if params[:q][:state_cont_any]
    end
  end

  def horses_filter
  end

  def studs_filter
  end

  def trailers_filter
  end

  def tacks_filter
  end

  def real_estates_filter
  end

  def services_filter
  end

  private 
    def set_search_horses
      @search_horses = Horse.search(params[:q])
    end

    def set_search_studs
      @search_studs = Stud.search(params[:q])
    end

    def set_search_trailers
      @search_trailers = Trailer.search(params[:q]) 
    end

    def set_search_tacks
      @search_tacks = Tack.search(params[:q])
    end

    def set_search_real_estates
      @search_real_estates = RealEstate.search(params[:q])
    end

    def set_search_services
      @search_services = Service.search(params[:q])
    end

    def set_search_horses_result
      if params[:q] 
        @horses = @search_horses.result
      else
        @horses = Horse.all;
      end
      @horses = @horses.live
    end

    def set_search_studs_result
      if params[:q] 
        @studs = @search_studs.result
      else
        @studs = Stud.all;
      end
      @studs = @studs.live
    end

    def set_search_trailers_result
      if params[:q] 
        @trailers = @search_trailers.result
      else
        @trailers = Trailer.all;
      end
      @trailers = @trailers.live
    end

    def set_search_tacks_result
      if params[:q] 
        @tacks = @search_tacks.result
      else
        @tacks = Tack.all;
      end
      @tacks = @tacks.live
    end

    def set_search_real_estates_result
      if params[:q] 
        @real_estates = @search_real_estates.result
      else
        @real_estates = RealEstate.all;
      end
      @real_estates = @real_estates.live
    end

    def set_search_services_result
      if params[:q] 
        @services = @search_services.result
      else
        @services = Service.all;
      end
      @services = @services.live
    end

    def set_breed_options
      @breeds = BreedOption.all.order(name: :asc)
    end

    def set_gender_options
      @genders = GenderOption.all.order(name: :asc)
    end

    def set_state_options
      @us_states = Carmen::Country.named('United States').subregions
      @ca_states = Carmen::Country.named('Canada').subregions
    end

    def set_ai_type_options
      @ai_types = AiTypeOption.all.order(name: :asc)
    end

    def set_hauls_options
      @hauls = Trailer.all.map(&:hauls).uniq
    end

    def set_tacks_options
      @tack_categories = TackOption.all.order(name: :asc)
      @tacks_type = TackTypeOption.all.order(name: :asc)
      @conditions = ConditionOption.all.order(name: :asc)
    end

    def set_house_options
      @house_types = HouseTypeOption.all.order(name: :asc)
      @bedrooms = RealEstate.all.map(&:bedroom).uniq.sort()
    end

    def set_service_options
      @service_types = ServiceTypeOption.all.order(name: :asc)
    end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/horses_result.js.erb
<%# Render list for XHR requests %>
<%= smart_listing_update :horses %>

<% if @horses %>
	<% horse_count = @horses.count  %>
<% else %>	
	<% horse_count = 0 %>
<% end %>
$('h4#result').text("<%= horse_count %> Horses Found");

app/views/home/real_estates.html.slim
.container.advanced-search
  #spin style="display:none;"
  = search_form_for @search_real_estates, url: real_estates_result_path, :html => {role: "form"} do |f|

    = render "home/shared/real_estate_checkbox"

    = f.submit "Search"

    hr

    - if @real_estates
      - real_estates_found = @real_estates.count
    - else 
      - real_estates_found = 0 
    h4#result= "#{real_estates_found} Real Estate Found"


javascript:
  var target = $('#spin');

  var house_types = [];
  $('form :checkbox[id^="q_house_type_cont_any_"]').click(function() {
    target.show();
    new Spinner().spin(target[0]);
    $('.advanced-search').css({opacity: '0.3'});
    if (this.checked) {
      house_types.push(this.value);
    } else {
      house_types.splice( $.inArray(this.value,house_types) ,1 );
    }
    
    console.log(house_types);
    
    $.get( '/real_estates-filter', { "q[house_type_cont_any][]": house_types, "q[bedroom_eq_any][]": bedrooms, "q[state_cont_any][]": states }, function(data) {
      target.hide();
      $('.advanced-search').css({opacity: '1'});
      
    });
    
  });


  var bedrooms = [];
  $('form :checkbox[id^="q_bedroom_eq_any_"]').click(function() {
    target.show();
    new Spinner().spin(target[0]);
    $('.advanced-search').css({opacity: '0.3'});
    if (this.checked) {
      bedrooms.push(this.value);
    } else {
      bedrooms.splice( $.inArray(this.value,bedrooms) ,1 );
    }
    
    console.log(bedrooms);
    
    $.get( '/real_estates-filter', { "q[house_type_cont_any][]": house_types, "q[bedroom_eq_any][]": bedrooms, "q[state_cont_any][]": states }, function(data) {
      target.hide();
      $('.advanced-search').css({opacity: '1'});
      
    });
    
  });


  var states = [];
  $('form :checkbox[id^="q_state_cont_any_"]').click(function() {
    target.show();
    new Spinner().spin(target[0]);
    $('.advanced-search').css({opacity: '0.3'});

    if (this.checked) {
      states.push(this.value);
    } else {
      states.splice( $.inArray(this.value, states) ,1 );
    }
    
    console.log(states);
    
    $.get( '/real_estates-filter', { "q[house_type_cont_any][]": house_types, "q[bedroom_eq_any][]": bedrooms, "q[state_cont_any][]": states }, function(data) {
      target.hide();
      $('.advanced-search').css({opacity: '1'});
    });
    
  });

app/views/home/real_estates_filter.js.erb
var checkboxes_house_type = $('form :checkbox[id^="q_house_type_cont_any_"]');
var checkboxes_bedroom = $('form :checkbox[id^="q_bedroom_eq_any_"]');
var checkboxes_state = $('form :checkbox[id^="q_state_cont_any_"]');

<% if @real_estates %>
	<% real_estate_count = @real_estates.count  %>
<% else %>	
	<% real_estate_count = 0 %>
<% end %>
$('h4#result').text("<%= real_estate_count %> Real Estate Found");

checkboxes_house_type.prop('disabled', false);
checkboxes_bedroom.prop('disabled', false);
checkboxes_state.prop('disabled', false);

<% if @real_estates %>

	var check_house_type = function() {
		checkboxes_house_type.prop('disabled', true);
		for (index = 0; index < checkboxes_house_type.length; ++index) {
			var checkbox = $('form :checkbox[id^="q_house_type_cont_any_"]:eq('+index+')');
			<% @real_estates.each do |real_estate| %>
				if (checkbox.is(':checked') || checkboxes_house_type[index].value === "<%= real_estate.house_type %>") {
			  	checkbox.prop('disabled', false);
				} 
			<% end %>
		}
	}

	var check_bedroom = function() {
		checkboxes_bedroom.prop('disabled', true);
		for (index = 0; index < checkboxes_bedroom.length; ++index) {
			var checkbox = $('form :checkbox[id^="q_bedroom_eq_any_"]:eq('+index+')');
			<% @real_estates.each do |real_estate| %>
				if (checkbox.is(':checked') || checkboxes_bedroom[index].value === "<%= real_estate.bedroom %>") {
			  	checkbox.prop('disabled', false);
				} 
			<% end %>
		}
	}

	var check_state =  function() {
		checkboxes_state.prop('disabled', true);
		for (index = 0; index < checkboxes_state.length; ++index) {
			var checkbox = $('form :checkbox[id^="q_state_cont_any_"]:eq('+index+')');
			<% @real_estates.each do |real_estate| %>
				if (checkbox.is(':checked') || checkboxes_state[index].value === "<%= real_estate.state %>") {
			  	checkbox.prop('disabled', false);
				}
			<% end %>
		}
	}


	<% if params[:q] %>
		<% if params[:q][:house_type_cont_any] %>
			check_bedroom();	
			check_state();
		<% end %>

		<% if params[:q][:bedroom_eq_any] %>
			check_house_type();
			check_state();
		<% end %>

		<% if params[:q][:state_cont_any] %>
			check_bedroom();
			check_house_type();
		<% end %>
	<% end %>
<% end %>

app/views/home/real_estates_result.html.slim
.container
	= smart_listing_controls_for(:real_estates) do
		= render "home/shared/real_estate_checkbox"

	- if @real_estates
		- real_estates_found = @real_estates.count
	- else 
		- real_estates_found = 0 

	h4#result= "#{real_estates_found} Real Estates Found"

	hr 
	= smart_listing_render :real_estates

= include_gon
= javascript_include_tag 'inspect_initial_checkbox', 'data-turbolinks-track' => true

app/views/home/services.html.slim
.container.advanced-search
  #spin style="display:none;"
  = search_form_for @search_services, url: services_result_path, :html => {role: "form"} do |f|

    = render "home/shared/services_checkbox"

    = f.submit "Search"

  hr

  - if @services
    - services_found = @services.count
  - else 
    - services_found = 0 
  h4#result= "#{services_found} Services Found"


javascript:
  var target = $('#spin');

  var service_types = [];
  $('form :checkbox[id^="q_service_type_cont_any_"]').click(function() {
    target.show();
    new Spinner().spin(target[0]);
    $('.advanced-search').css({opacity: '0.3'});
    if (this.checked) {
      service_types.push(this.value);
    } else {
      service_types.splice( $.inArray(this.value,service_types) ,1 );
    }
    
    console.log(service_types);
    
    $.get( '/services-filter', { "q[service_type_cont_any][]": service_types, "q[state_cont_any][]": states }, function(data) {
      target.hide();
      $('.advanced-search').css({opacity: '1'});
    });
    
  });

  var states = [];
  $('form :checkbox[id^="q_state_cont_any_"]').click(function() {
    target.show();
    new Spinner().spin(target[0]);
    $('.advanced-search').css({opacity: '0.3'});

    if (this.checked) {
      states.push(this.value);
    } else {
      states.splice( $.inArray(this.value, states) ,1 );
    }
    
    console.log(states);
    
    $.get( '/services-filter', { "q[service_type_cont_any][]": service_types, "q[state_cont_any][]": states }, function(data) {
      target.hide();
      $('.advanced-search').css({opacity: '1'});
    });
    
  });

app/views/home/services_result.js.erb
<%# Render list for XHR requests %>
<%= smart_listing_update :services %>

<% if @services %>
	<% service_count = @services.count  %>
<% else %>	
	<% service_count = 0 %>
<% end %>
$('h4#result').text("<%= service_count %> Services Found");

app/views/home/studs.html.slim
.container.advanced-search
	#spin style="display:none;"
	= search_form_for @search_studs, url: studs_result_path, :html => {role: "form"} do |f|

		= render "home/shared/studs_checkbox"
			
		= f.submit "Search"
 

	hr

	- if @studs
		- studs_found = @studs.count
	- else 
		- studs_found = 0 
	h4#result= "#{studs_found} Studs Found"


javascript:
	var target = $('#spin');

	var breeds = [];
	$('form :checkbox[id^="q_breed_cont_any_"]').click(function() {
		target.show();
		new Spinner().spin(target[0]);
		$('.advanced-search').css({opacity: '0.3'});
		if (this.checked) {
			breeds.push(this.value);
		} else {
			breeds.splice( $.inArray(this.value,breeds) ,1 );
		}
		
		console.log(breeds);
		
    $.get( '/studs-filter', { "q[breed_cont_any][]": breeds, "q[ai_type_cont_any][]": ai_types, "q[state_cont_any][]": states }, function(data) {
    	target.hide();
    	$('.advanced-search').css({opacity: '1'});
    });
    
	});

	var ai_types = [];
	$('form :checkbox[id^="q_ai_type_cont_any_"]').click(function() {

		target.show();
		new Spinner().spin(target[0]);
		$('.advanced-search').css({opacity: '0.3'});
		if (this.checked) {
			ai_types.push(this.value);
		} else {
			ai_types.splice( $.inArray(this.value,ai_types) ,1 );
		}
		
		console.log(ai_types);
		
    $.get( '/studs-filter', { "q[breed_cont_any][]": breeds, "q[ai_type_cont_any][]": ai_types, "q[state_cont_any][]": states }, function(data) {
    	target.hide();
    	$('.advanced-search').css({opacity: '1'});
    });
    
	});


	var states = [];
	$('form :checkbox[id^="q_state_cont_any_"]').click(function() {
		target.show();
		new Spinner().spin(target[0]);
		$('.advanced-search').css({opacity: '0.3'});
		if (this.checked) {
			states.push(this.value);
		} else {
			states.splice( $.inArray(this.value, states) ,1 );
		}
		
		console.log(states);
		
    $.get( '/studs-filter', { "q[breed_cont_any][]": breeds, "q[ai_type_cont_any][]": ai_types, "q[state_cont_any][]": states }, function(data) {
    	target.hide();
    	$('.advanced-search').css({opacity: '1'});
    });
    
	});

app/views/home/studs_result.html.slim
.container
	= smart_listing_controls_for(:studs) do
		= render "home/shared/studs_checkbox"

	- if @studs
		h4#result= "#{@studs.count} Stud Found"
	- else
		h4#result Stud Not Found

	hr
	= smart_listing_render :studs

= include_gon
= javascript_include_tag 'inspect_initial_checkbox', 'data-turbolinks-track' => true

app/views/home/studs_result.js.erb
<%# Render list for XHR requests %>
<%= smart_listing_update :studs %>

<% if @studs %>
	<% stud_count = @studs.count  %>
<% else %>	
	<% stud_count = 0 %>
<% end %>
$('h4#result').text("<%= stud_count %> Studs Found");

app/views/home/tacks_result.html.slim
.container
	= smart_listing_controls_for(:tacks) do
		= render "home/shared/tacks_checkbox"

	- if @tacks
		- tacks_found = @tacks.count
	- else 
		- tacks_found = 0 

	h4#result= "#{tacks_found} Tack Found"

	= smart_listing_render :tacks

= include_gon
= javascript_include_tag 'inspect_initial_checkbox', 'data-turbolinks-track' => true

app/views/home/tacks_result.js.erb
<%# Render list for XHR requests %>
<%= smart_listing_update :tacks %>

<% if @tacks %>
	<% tack_count = @tacks.count  %>
<% else %>	
	<% tack_count = 0 %>
<% end %>
$('h4#result').text("<%= tack_count %> Tacks Found");

app/views/home/trailers.html.slim
.container.advanced-search
  #spin style="display:none;"
  = search_form_for @search_trailers, url: trailers_result_path, :html => {role: "form"} do |f|

    = render "home/shared/trailers_checkbox"

    = f.submit "Search"

  hr

  - if @trailers
    - trailers_found = @trailers.count
  - else 
    - trailers_found = 0 
  h4#result= "#{trailers_found} Trailer Found"


javascript:
  var target = $('#spin');

  var hauls = [];
  $('form :checkbox[id^="q_hauls_eq_any_"]').click(function() {
    target.show();
    new Spinner().spin(target[0]);
    $('.advanced-search').css({opacity: '0.3'});
    if (this.checked) {
      hauls.push(this.value);
    } else {
      hauls.splice( $.inArray(this.value,hauls) ,1 );
    }
    
    console.log(hauls);
    
    $.get( '/trailers-filter', { "q[hauls_eq_any][]": hauls, "q[state_cont_any][]": states }, function(data) {
      target.hide();
      $('.advanced-search').css({opacity: '1'});
      
    });
    
  });

  var states = [];
  $('form :checkbox[id^="q_state_cont_any_"]').click(function() {
    target.show();
    new Spinner().spin(target[0]);
    $('.advanced-search').css({opacity: '0.3'});

    if (this.checked) {
      states.push(this.value);
    } else {
      states.splice( $.inArray(this.value, states) ,1 );
    }
    
    console.log(states);
    
    $.get( '/trailers-filter', { "q[state_cont_any][]": states }, function(data) {
      target.hide();
      $('.advanced-search').css({opacity: '1'});
    });
    
  });

app/views/home/trailers_result.html.slim
.container
	= smart_listing_controls_for(:trailers) do
		= render "home/shared/trailers_checkbox"

	- if @trailers
		- trailers_found = @trailers.count
	- else 
		- trailers_found = 0 

	h4#result= "#{trailers_found} Trailer Found"

	hr
	= smart_listing_render :trailers

= include_gon
= javascript_include_tag 'inspect_initial_checkbox', 'data-turbolinks-track' => true

app/views/home/trailers_result.js.erb
<%# Render list for XHR requests %>
<%= smart_listing_update :trailers %>

<% if @trailers %>
	<% trailer_count = @trailers.count  %>
<% else %>	
	<% trailer_count = 0 %>
<% end %>
$('h4#result').text("<%= trailer_count %> Trailers Found");