config/routes.rb
Rails.application.routes.draw do

 
  match '/oauth2callback', :to => 'oauth2_callbacks#google', :as => 'google_oauth2', :via => [:get]

  match '/payments/payment', :to => 'payments#payment', :as => 'paymentspayment', :via => [:get]
  match '/payments/relay_response', :to => 'payments#relay_response', :as => 'payments_relay_response', :via => [:post]
  match '/payments/receipt', :to => 'payments#receipt', :as => 'payments_receipt', :via => [:get]
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  root 'home#index'

  items = %w( horses studs trailers tacks real_estates services )
 
  items.each do |item|
    resources item.to_sym do
      collection do
        get 'search'
        get 'youtube_upload'
      end
      member do
        get 'search'
      end
    end
  end
 
  resources :packages do
    items.each do |item|
      resources item.to_sym, shallow: true do
        member do
          get 'preview', to: "#{item}#preview"
          get 'publish', to: "#{item}#publish"
          get 'unpublish', to: "#{item}#unpublish"
          get 'sold', to: "#{item}#sold"
          get 'activate', to: "#{item}#activate"
          get 'unactivate', to: "#{item}#unactivate"
          get 'mark-sold', to: "#{item}#mark_sold"
        end
      end
    end
  end

  resources :users do
    items.each do |item|
      resources item.to_sym do
        member do
          get "like"
          get "dislike"
        end
      end
    end 
  end

  resources :profiles do
    member do
      get 'ads'
      get 'about'
      get 'favorites'
    end
    collection do
      get 'ads'
      get 'about'
      get 'favorites'
    end
  end


  get 'pricing' => 'home#pricing', :as => :pricing

  get 'search-horses' => 'home#horses', as: :home_horses
  get 'search-studs' => 'home#studs', as: :home_studs
  get 'search-tacks' => 'home#tacks', as: :home_tacks
  get 'search-real-estates' => 'home#real_estates', as: :home_real_estates
  get 'search-services' => 'home#services', as: :home_services
  get 'search-trailers' => 'home#trailers', as: :home_trailers

  get 'horses-result' => 'home#horses_result', as: :horses_result
  get 'horses-filter' => 'home#horses_filter', as: :horses_filter

  get 'studs-result' => 'home#studs_result', as: :studs_result
  get 'studs-filter' => 'home#studs_filter', as: :studs_filter

  get 'trailers-result' => 'home#trailers_result', as: :trailers_result
  get 'trailers-filter' => 'home#trailers_filter', as: :trailers_filter

  get 'tacks-result' => 'home#tacks_result', as: :tacks_result
  get 'tacks-filter' => 'home#tacks_filter', as: :tacks_filter

  get 'real_estates-result' => 'home#real_estates_result', as: :real_estates_result
  get 'real_estates-filter' => 'home#real_estates_filter', as: :real_estates_filter

  get 'services-result' => 'home#services_result', as: :services_result
  get 'services-filter' => 'home#services_filter', as: :services_filter

end

app/models/stud.rb
class Stud < ActiveRecord::Base
	include AASM

	belongs_to :package
	belongs_to :user
	has_many :pictures, as: :imageable, dependent: :destroy
	has_many :videos, as: :videoable, dependent: :destroy

	has_many :disciplines, as: :discipline, dependent: :destroy

	accepts_nested_attributes_for :disciplines

	#validates :title, :description, :city, :state, :zip_code,:breed, :birth, :user_name, :email, :stud_fee, :booking_fee, presence: true

	#validates :email, :email_format => {:message => 'is not looking good'}

	#validates :stud_fee, :booking_fee, numericality: { greater_than_or_equal_to: 0 }

	accepts_nested_attributes_for :disciplines

	is_impressionable :counter_cache => true, :column_name => :views_count, :unique => :ip_address
	acts_as_votable

	aasm column: 'status' do
    state :draft, initial: true
    state :published
    state :removed
    state :booked

    event :publish do
      transitions from: :draft, to: :published
    end

    event :make_draft do
      transitions from: :published, to: :draft
    end

    event :make_booked do
      transitions from: :published, to: :booked
    end

    event :to_booked do
      transitions from: :removed, to: :booked
    end

  end

	# Ad Stud in range of duration
	scope :published, -> { where(status: 'published') }

	scope :live, -> { where("published_end > ?", "%#{DateTime.now}%" ) }

	featured_packages = ["Deluxe", "Premium"]
	scope :featured_ad, -> { where(package_id: Package.where(name: featured_packages).map(&:id)) }
	
	scope :newest_ad, -> { order(published_at: :desc) }

	scope :favorited_by, ->(user) { where(id: user.find_liked_items.map(&:id)) }

	
	def ad_banner
		self.pictures.find(self.banner) if self.pictures.present?
	end
end

app/controllers/studs_controller.rb
class StudsController < ApplicationController
  before_action :set_user, only: [:like, :dislike]
  before_action :set_stud, except: [:index, :create, :search, :new]
  before_action :authenticate_user!, only: [:new, :like, :dislike]
  before_action :set_items_gallery, only: [:show, :preview]

  impressionist :actions=>[:show]

  include SmartListing::Helper::ControllerExtensions
  helper  SmartListing::Helper

  def index
    @studs = Stud.all
  end

   # GET /studs/1
  def show
  end

  # GET /packages/:package_id/studs/new
  def new
    @stud = Package.find(params[:package_id]).studs.new
    @stud.disciplines.new
    gon.image_upload_limit = @stud.package.max_photo_upload
    gon.video_upload_limit = @stud.package.max_video_upload
  end

  # GET /studs/:id/edit
  def edit
  end

  # POST /packages/:package_id/studs
  # TODO -> Refactor this method
  def create
    @stud = Stud.new(stud_params)
    @stud.user_id = current_user.id
    
    respond_to do |format|
      if @stud.save 
        unless params[:stud][:pictures].nil?
          params[:stud][:pictures].each do |picture|
             @stud.pictures.create(name: picture)
          end
          @stud.update(banner: @stud.pictures.first.id)
        end

        unless params[:stud][:videos].nil?
          params[:stud][:videos].each do |video|
             @stud.videos.create(name: video)
          end
        end

        format.html { redirect_to preview_stud_url(@stud), notice: 'Ad Stud Saved!' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /studs/:id
  # TODO -> update for studs picture & video
  def update
    respond_to do |format|
      if @stud.update(stud_params)
        format.html { redirect_to preview_stud_url(@stud), notice: 'Stud was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /studs/:id
  def destroy
    @stud.destroy
    respond_to do |format|
      format.html { redirect_to ads_profiles_url }
    end
  end

  # GET /horses/:id/preview
  def preview
  end

  # GET /horses/:id/publish
  def publish
  end

  # GET /horses/:id/unpublish
  def unpublish
  end


  # GET /horses/:id/activate
  def activate
    respond_to do |format|
      if @stud.draft?
        @stud.publish!
        @stud.update(published_at: DateTime.now,
          published_end: DateTime.now + @stud.package.duration.month)
        format.html { redirect_to @stud, notice: 'Ad was successfully published.' }
      else
        format.html { render :preview }
      end
    end
  end

  # GET /horses/:id/unactivate
  def unactivate
    respond_to do |format|
      if @stud.published?
        @stud.remove!
        format.html { redirect_to ads_profiles_url, notice: 'Ad was successfully unpublished.' }
      else
        format.html { redirect_to unpublish_stud_url }
      end
    end
  end

  # GET /horses/:id/sold
  def sold
  end

  # GET /horses/:id/mark-sold
  def mark_sold
    respond_to do |format|
      if @stud.published? || @stud.removed?
        @stud.make_sold! if @stud.published?
        @stud.to_sold! if @stud.removed?
        format.html { redirect_to ads_profiles_url, notice: 'Ad was successfully Mark As Sold' }
      else
        format.html { redirect_to sold_stud_url }
      end
    end
  end

  def like
    @stud.liked_by @user
  end

  def dislike
    @stud.unliked_by @user
  end

  def search
    unless params[:q].empty?
      @params_q = params[:q]
      @studs =  Stud.search(params[:q]).result
    else
      @studs = Stud.all
    end

    sort_by = {updated_at: :desc} if params[:sort_by] == "newest" || params[:sort_by].nil?
    sort_by = {updated_at: :asc} if params[:sort_by] == "oldest"
    sort_by = {price: :desc} if params[:sort_by] == "high_to_low"
    sort_by = {price: :asc} if params[:sort_by] == "low_to_high"

    @studs =  @studs.order(sort_by).published.live

    smart_listing_create(:studs, @studs, partial: "studs/stud_list")

  end

  private 
    # Use callbacks to share common setup or constraints between actions.
    def set_stud
      @stud = Stud.find(params[:id])
    end

    def set_user
      @user = User.find(params[:user_id])
    end

    def set_items_gallery
      @items_gallery = @stud.pictures + @stud.videos
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stud_params
      params.require(:stud).permit(:title, :description, :name,
        :breed, :city, :state, :zip_code, :private_treaty, :ai_type,
        :birth, :color, :height, :weight, :package_id, :registration, :registration_num,
        :second_reg, :second_reg_num, :other_markings, :second_breed, :temperament, 
        :stud_fee, :booking_fee, :shipping_fee, :available, :until, :ai_type,
        :user_name, :farm_name, :email, :website, :phone_number, :alt_phone_number,
        disciplines_attributes: [:id, :name, :experience, :_destroy])
    end
end

app/helpers/studs_helper.rb
module StudsHelper
end

app/views/studs/_form.html.slim
= simple_nested_form_for @stud, html: {multipart: true, class: 'form-horizontal'} do |f|

  - if @stud.errors.any?
    #error_explanation
      h2 = "#{pluralize(@stud.errors.count, "error")} prohibited this horse from being saved:"
      ul
        - @stud.errors.full_messages.each do |message|
          li = message

  .document.border-bottom
    .document-wrapper.border
      .text.ten
        h2.followon The Basics About Your Horse
        
        .row
          = f.hidden_field :package_id, value: @stud.package_id
          = f.input :title, label: false, placeholder: "Ad Title * - Captive Your Buyer"
          = f.input :description, label: false,  placeholder: "About Your Horse * - Personality, Talents & Experience", input_html: { rows: 8 } 

        .row
          = f.input :name, label: false, wrapper_html: { class: 'col-md-6' }, placeholder: "Horse's Name (optional)"
          = f.input :ai_type, label: false, wrapper_html: { class: 'col-md-6' }, prompt: "AI Type *", collection: AiTypeOption.all, value_method: :name

        .row
          = f.input :zip_code, label: false, wrapper_html: { class: 'col-md-4' }, placeholder: "*Zip Code*"
          = f.input :city, label: false, wrapper_html: { class: 'col-md-4' }, placeholder: "City"
          = f.input :state, label: false, wrapper_html: { class: 'col-md-4' }, placeholder: "State/Province*"
          

        .row
          = f.input :stud_fee, label: false, wrapper_html: { class: 'col-md-4' }, placeholder: "$ Stud Fee *"
          = f.input :booking_fee, label: false, wrapper_html: { class: 'col-md-4' }, placeholder: "$ booking Fee *"

        .row
          = f.input :shipping_fee, label: false, wrapper_html: { class: 'col-md-4' }, placeholder: "$ Shipping Fee"
          = f.input :private_treaty, label: false, inline_label: true, wrapper_html: { class: 'col-md-4' }

        h3 Breeding Available

        .row
          = f.input :available, label: false, discard_year: true, prompt: { month: 'Month Available (optional)', day: 'Day Available (optional)' }

          = f.input :until, label: false, discard_year: true, prompt: { month: 'Month Until (optional)', day: 'Day Until (optional)' }

  .document.border-bottom
    .document-wrapper.border
      .text.ten
        h2.followon Details & Breed Information
        .row
          = f.input :birth, label: false, :start_year => Date.today.year - 12, :end_year => Date.today.year, discard_day: true, prompt: { month: 'Birth Month (optional)', year: 'Birth Year *' }

        .row
          = f.input :color, label: false, wrapper_html: { class: 'col-md-6' }, prompt: "Color (optional)", collection: ColorOption.all, value_method: :name
          = f.input :other_markings, label: false, wrapper_html: { class: 'col-md-6' }, placeholder: "Other Markings (optional)"

        .row
          = f.input :height, label: false, wrapper_html: { class: 'col-md-6' }, placeholder: "Height (optional)"
          = f.input :weight, label: false, wrapper_html: { class: 'col-md-6' }, placeholder: "Weight (lbs) (optional)"

        .row
          = f.input :breed, label: false, wrapper_html: { class: 'col-md-6' }, prompt: "Breed *", collection: BreedOption.all, value_method: :name
          = f.input :second_breed, label: false, wrapper_html: { class: 'col-md-6' }, prompt: "Secondary Breed (optional)", collection: BreedOption.all, value_method: :name

        = render "shared/form/registry_info", f: f

  .document.border-bottom
    .document-wrapper.border
      .text.ten
        = render "shared/form/personality_and_experience", f: f

  - unless @stud.package.name == "Basic"
    = render "shared/form/input_file", f: f
    
  = render "shared/form/contact_info", f: f
  
  = render "shared/form/terms_and_conditions", f: f

  = render "shared/form/submit_button", f: f

javascript:
  $('select[id*="stud_birth"]').wrap('<div class="col-md-6">');
  $('select[id*="stud_available"]').wrap('<div class="col-md-6">');
  $('select[id*="stud_until"]').wrap('<div class="col-md-6">');

app/views/studs/_stud_detail.html.slim
.preview-wrapper
  .row
    .col-md-6
      - unless @stud.ad_banner.nil?
        img src= @stud.ad_banner.name.thumb.url
      - else
        =image_tag( 'horse1.jpg')
    .col-md-6
      h4 
        - unless @stud.name.nil?
          = @stud.name
        - else
          | UNNAMED
      .price
        - unless @stud.private_treaty
          = "Stud Fee: #{number_to_currency @stud.stud_fee}"
          br /
          = "Booking Fee: #{number_to_currency @stud.booking_fee}"
          br /
          = "Shipping Fee:  #{number_to_currency @stud.shipping_fee}"
          br /
        - else
          | PRIVATE TREATY
      hr

      .short_detail
        = "#{@stud.birth.year} #{@stud.breed} stallion"
        br
        = "#{@stud.height} Hands"
        br
        = "Located in #{@stud.state}"
        br
        = "Stud by #{@stud.user.username}"

  .row
    .col-md-12.stats
      h4 HORSES STATS
      hr
      table.table.table-striped
        tr
          td Name
          td= @stud.name
        tr
          td Color
          td= @stud.color.titleize
        tr
          td Breed
          td= @stud.breed
        tr
          td Age
          td= @stud.birth
        tr
          td Height
          td= "#{@stud.height} hands"
        tr
          td Weight
          td= "#{@stud.weight} lbs"

  .row
    .col-md-12
      h4= @stud.title.upcase
      hr
      p= @stud.description

  .row
    .col-md-12.galleries
      h4 PHOTO & VIDEO GALLERY
      hr
      - @items_gallery.in_groups_of(4).each do |item_group|
        .row
          - item_group.each do |item|
            - unless item.nil?
              .col-md-3
                =image_tag item.name.thumb

  .row
    .col-md-12
      h4 CONTACT SELLER
      hr
      - if @stud.user.profile.user_picture.present?
        img src=  @stud.user.profile.user_picture.avatar.url
      - else
        .fa-stack.fa-4x
          i.fa.fa-circle.fa-stack-2x
          i.fa.fa-user.fa-stack-1x.fa-inverse

     
      - if @stud.user.profile.name.present?
        p= "FOR SALE BY #{@stud.user.profile.name.upcase}"
      - else
        p= "FOR SALE BY #{@stud.user.username.upcase}"

      - if @stud.user.profile.state && @stud.user.profile.city
        p= "#{@stud.user.profile.state}, #{@stud.user.profile.city}"

      ul.nav.nav-tabs
        li
          i.fa.fa-envelope.fa-2x
          br EMAIL SELLER
        | &nbsp;&nbsp;
        - if @stud.user.profile.phone_number.present?
          li
            i.fa.fa-phone.fa-2x&nbsp
            br= @stud.user.profile.phone_number
          | &nbsp;&nbsp;
        - if @stud.user.profile.name.present?
          li
            =link_to ads_profile_path(@stud.user)
              i.fa.fa-bookmark.fa-2x&nbsp
              br VIEW ALL ADS
          | &nbsp;&nbsp;
        - if @stud.user.profile.name.present?
          li
            a href="http://#{@stud.user.profile.website}"
              i.fa.fa-globe.fa-2x&nbsp
              br VIEW WEBSITE

app/views/studs/_stud_list.html.slim
- unless smart_listing.empty? 
  
  - smart_listing.collection.in_groups_of(4).each do |horses_group|
    .row
      ul.thumbnails
        - horses_group.each do |horse|
          - unless horse.nil?
            .li.col-md-3
              = render partial: "shared/horse_thumbnail", locals: {horse: horse}

  = smart_listing.paginate

app/views/studs/edit.html.slim
.container
  .form-wrapper
  	= render "form"

.static-bottom
	= link_to 'Destroy', @stud, class: "btn", method: :delete, \
            data: {confirm: 'Are you sure?'} 
 	= link_to 'Cancel', ads_profiles_path, class: "btn"

app/views/studs/new.html.slim
section#profile
	.container
		header.profile_header
			h1= "Create Your #{@stud.package.name} Stud Ad"
		.outer
			.inner.pt-0
				= render "form"

= include_gon
= javascript_include_tag 'inspect_file_upload_limit', 'data-turbolinks-track' => true

app/views/studs/preview.html.slim
.container
  .preview-wrapper
    h1 Preview Your Draft
    
    = render "stud_detail"
          
    = link_to 'Edit', edit_stud_path(@stud), class: "btn btn-primary btn-inverse"
    | &nbsp;
    = link_to 'Publish Ad', publish_stud_path(@stud), class: "btn btn-primary btn-inverse"

app/views/studs/publish.html.slim
.container
  .publish-wrapper
    h1 Publish Your Stud
    
    - unless @stud.ad_banner.nil?
      img src= @stud.ad_banner.name.thumb.url
    - else
      =image_tag( 'horse1.jpg')

    p= "#{@stud.package.name} Ad Package"
    p= "TOTAL #{number_to_currency @stud.package.price}"

    h4= "YOUR #{@stud.package.name.upcase} AD INCLUDES"
    ul
    	li= "#{@stud.package.duration} Month Ad Duration"
    	- if @stud.package.max_photo_upload > 0
    		li= "Up To #{@stud.package.max_photo_upload} Photos"
    	- if @stud.package.max_video_upload > 0
    		li= "Up To #{@stud.package.max_video_upload} Videos"

          
    = link_to 'Edit', edit_stud_path(@stud), class: "btn btn-primary btn-inverse"
    | &nbsp;
    = link_to 'Publish', activate_stud_path(@stud), class: "btn btn-primary btn-inverse"

app/views/studs/search.html.slim
.container
  h4= "#{@studs.count} Stallion Found" 

  .row.filter
    .col-md-10

    .col-md-2
      = smart_listing_controls_for(:studs, {class: "form-inline text-right"}) do
        =select_tag :sort_by, options_for_select([["Newest", "newest"], ["Oldest", "oldest"], ["Price High to Low", "high_to_low"], ["Price Low to High", "low_to_high"] ], "newest"), { class: 'form-control' } 

        - unless @params_q.nil?
          =hidden_field_tag "q[breed_cont]", @params_q["breed_cont"]
          =hidden_field_tag "q[state_cont]", @params_q["state_cont"]
          =hidden_field_tag "q[city_cont]", @params_q["city_cont"]
          =hidden_field_tag "q[price_gteq]", @params_q["price_gteq"]
          =hidden_field_tag "q[price_lteq]", @params_q["price_lteq"]


  = smart_listing_render :studs
  
= javascript_include_tag 'fav_button', 'data-turbolinks-track' => true

app/views/studs/search.js.erb
<%# Render list for XHR requests %>
<%= smart_listing_update :studs %>

app/views/studs/show.html.slim
.container
  h1 Show Stud
  = render "stud_detail"

app/views/studs/sold.html.slim
.container
  .sold-wrapper
    h1 MARK YOUR AD AS SOLD

    h4 CONGRATULATIONS ON SELLING YOUR TUCK!

    = link_to 'Cancel', ads_profiles_path, class: "btn"
    = link_to 'Mark As Sold', mark_stud_tack_path(@stud), class: "btn"

app/views/studs/unpublish.html.slim
.container
  .unpublish-wrapper
    h1 Unpublish Your STUD

    p 
      | Unpublishing your ad will hide it from public view. However, you will be able to republish it at any time before your ad's expiration date.

    = link_to 'Cancel', ads_profiles_path, class: "btn"
    = link_to 'Unpublish', unactivate_real_estate_path(@stud), class: "btn"